### PR TITLE
Bump sbt version to latest patch release

### PR DESCRIPTION
**Pull request by jsravn**

### CODE REVIEW

**Comment by dwijnand** [comment]
Failed with:

```
~/stage
dpkg-deb: building package 'reactive-cli' in 'package.deb'.
[info] [ubuntu-older] building
[info] [ubuntu-older] copying project
Error response from daemon: Get https://lightbend-docker-registry.bintray.io/v2/rp/reactive-cli-build-ubuntu-older/manifests/latest: Get https://lightbend-docker-registry.bintray.io/v2/token?scope=repository%3Arp%2Freactive-cli-build-ubuntu-older%3Apull&service=lightbend-docker-registry.bintray.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
java.lang.AssertionError: assertion failed: Executing WrappedArray(docker, pull, lightbend-docker-registry.bintray.io/rp/reactive-cli-build-ubuntu-older:latest) yielded 1, expected 0
	at scala.Predef$.assert(Predef.scala:179)
	at AdditionalIO$.runProcess(AdditionalIO.scala:9)
	at BuildInfo.pullImage$1(BuildInfo.scala:278)
	at BuildInfo.run(BuildInfo.scala:308)
	at $4bfa4ea5d2c8ef400283$$anonfun$root$11$$anonfun$apply$16.apply(build.sbt:169)
```

I presume this is just build flakiness, as opposed to caused by this change.

**Comment by dwijnand** [comment]
Triggered a build of current master to see what happens: https://travis-ci.org/lightbend/reactive-cli/builds/402678734

**Comment by jsravn** [comment]
Snuck in a small change to the README.md, took me a while to figure out to get reactive-cli happy in IntelliJ (tl;dr delete scala-native lib).

**Comment by dwijnand** [comment]
Nice one. I have vague memories of doing something along those lines. Good idea to document it.

**Pull request merged**
