### PR TITLE
Support connection to Docker private registry

### PR DESCRIPTION
**Pull request by fsat**
This PR will allow Reactive CLI to connect to Docker private registry.

The following connectivity options are available:
* Allowing for both `http` or `https` connectivity.
* Disabling TLS validation to allow connectivity to private registry with self-signed cert.
* Specifying custom CA information to allow connectivity to private registry with self-signed cert.
* Allowing user to specify username and password which is used to connect to the private registry.

---
* [x] Input args to disable SSL and SSL cert validation.
* [x] Allow disabling SSL when accessing docker registry.
* [x] Allow disabling SSL validation when accessing docker registry.
* [x] Specify location of the `CACERTS` when validating SSL cert: https://curl.haxx.se/libcurl/c/CURLOPT_CAINFO.html
* [x] Expose environment variable to control CACERT location - environment variable name to match option switch with uppercase & underscore with `RP_` prefix, i.e. `RP_TLS_CACERTS_PATH`
* [x] Support docker registry base64 authentication.
* [ ] Manual test

### CODE REVIEW

**Comment by fsat** [comment]
**Manual Test: Setup**

Publish a Lagom docker image:

```
Felixs-MBP-2:docker-registry-scripts felixsatyaputra$ docker images
REPOSITORY                                                                                    TAG                       IMAGE ID            CREATED             SIZE
fsat/testimpl                                                                                 1.0.0-SNAPSHOT            2baa6af39b92        2 weeks ago         837MB
```

Generate self-signed cert:

```
openssl req \
  -newkey rsa:4096 -nodes -sha256 -keyout certs/domain.key \
  -x509 -days 365 -out certs/domain.crt
```

Start `http` registry:

```
docker run -d -p 5000:5000 --restart=always --name registry-non-secure registry:2
```

Start `https` registry:

```
docker run -d \
  --restart=always \
  --name registry-secure \
  -v `pwd`/certs:/certs \
  -e REGISTRY_HTTP_ADDR=0.0.0.0:5001 \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
  -p 5001:5001 \
  registry:2
```

Push the image to `http` registry. (`Layer already exists` is shown because this is a subsequent push).

```
Felixs-MBP-2:docker-registry-scripts felixsatyaputra$ docker tag 2baa6af39b92 localhost:5000/foo/testimpl:1.0.0-SNAPSHOT
Felixs-MBP-2:docker-registry-scripts felixsatyaputra$ docker push localhost:5000/foo/testimpl:1.0.0-SNAPSHOT
The push refers to a repository [localhost:5000/foo/testimpl]
c179573a6197: Layer already exists
47801e48a961: Layer already exists
3e93e187afd7: Layer already exists
9b790cee2175: Layer already exists
348667646bbd: Layer already exists
1d381f39fece: Layer already exists
e6683fd09097: Layer already exists
ffe8422597ee: Layer already exists
c2dca236d8e6: Layer already exists
d4417cb76edb: Layer already exists
0dc1ec77adb3: Layer already exists
a75caa09eb1f: Layer already exists
1.0.0-SNAPSHOT: digest: sha256:0fad493ffacdf57e96d266da5f1010665182df6c95c743e8b3944a11f2dd5255 size: 2843
```

Push the image to `https` registry. (`Layer already exists` is shown because this is a subsequent push).

```
Felixs-MBP-2:docker-registry-scripts felixsatyaputra$ docker tag 2baa6af39b92 localhost:5001/foo/testimpl:1.0.0-SNAPSHOT
Felixs-MBP-2:docker-registry-scripts felixsatyaputra$ docker push localhost:5001/foo/testimpl:1.0.0-SNAPSHOT
The push refers to a repository [localhost:5001/foo/testimpl]
c179573a6197: Layer already exists
47801e48a961: Layer already exists
3e93e187afd7: Layer already exists
9b790cee2175: Layer already exists
348667646bbd: Layer already exists
1d381f39fece: Layer already exists
e6683fd09097: Layer already exists
ffe8422597ee: Layer already exists
c2dca236d8e6: Layer already exists
d4417cb76edb: Layer already exists
0dc1ec77adb3: Layer already exists
a75caa09eb1f: Layer already exists
1.0.0-SNAPSHOT: digest: sha256:0fad493ffacdf57e96d266da5f1010665182df6c95c743e8b3944a11f2dd5255 size: 2843
```

**Comment by fsat** [comment]
**Manual Test: HTTP**

Artefact can be generated from HTTP based registry by specifiying `--registry-https-disable`.

```
192-168-1-5:reactive-cli felixsatyaputra$ ./cli/target/scala-2.11/reactive-cli-out generate-deployment localhost:5000/foo/testimpl:1.0.0-SNAPSHOT --target kubernetes --kubernetes-version 1.6 --registry-https-disable
---
{"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"name":"testImpl-v1.0.0-SNAPSHOT","labels":{"app":"testImpl","appVersionMajor":"testImpl-v1","appVersionMajorMinor":"testImpl-v1.0","appVersion":"testImpl-v1.0.0-SNAPSHOT"}},"spec":{"replicas":1,"serviceName":"testImpl-v1","template":{"app":"testImpl","appVersionMajor":"testImpl-v1","appVersionMajorMinor":"testImpl-v1.0","appVersion":"testImpl-v1.0.0-SNAPSHOT"},"spec":{"containers":[{"name":"testImpl","image":"localhost:5000/foo/testimpl:1.0.0-SNAPSHOT","imagePullPolicy":"IfNotPresent","env":[{"name":"FOO","value":"123"},{"name":"RP_ENDPOINTS","value":"TA-V1"},{"name":"RP_ENDPOINTS_COUNT","value":"1"},{"name":"RP_ENDPOINT_0_PORT","value":"16668"},{"name":"RP_ENDPOINT_TA-V1_PORT","value":"16668"},{"name":"RP_KUBERNETES_POD_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}},{"name":"RP_KUBERNETES_POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"RP_PLATFORM","value":"kubernetes"},{"name":"RP_VERSION","value":"1.0.0-SNAPSHOT"},{"name":"RP_VERSION_MAJOR","value":"1"},{"name":"RP_VERSION_MINOR","value":"0"},{"name":"RP_VERSION_PATCH","value":"0"},{"name":"RP_VERSION_PATCH_LABEL","value":"SNAPSHOT"}],"ports":[{"containerPort":16668,"name":"ta-v1"}],"readinessProbe":{"httpGet":{"path":"/healthz","port":1234},"periodSeconds":60},"livenessProbe":{"exec":{"command":["/bin/bash","-c","exit 0"]}}}]}}}
---
{"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app":"testImpl"},"name":"testImpl"},"spec":{"clusterIP":"None","ports":[{"name":"ta-v1","port":16668,"protocol":"TCP","targetPort":16668}],"selector":{"app":"testImpl"}}}
---
{"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"name":"testImpl"},"spec":{"rules":[{"http":{"paths":[{"path":"^/ta.*$","backend":{"serviceName":"ta-v1","servicePort":16668}}]}}]}}
```

**Comment by fsat** [comment]
**Manual Test: HTTPS**

Self-signed cert will generate HTTPS related error:

```
192-168-1-5:reactive-cli felixsatyaputra$ ./cli/target/scala-2.11/reactive-cli-out generate-deployment localhost:5001/foo/testimpl:1.0.0-SNAPSHOT --target kubernetes --kubernetes-version 1.6
curl_easy_perform() failed: Peer certificate cannot be authenticated with given CA certificates
[error, com.lightbend.rp.reactivecli.Main$] Failure generating kubernetes resources for docker image localhost:5001/foo/testimpl:1.0.0-SNAPSHOT
```

Artefact can be generated from HTTP based registry by specifiying `--registry-tls-validation-disable`.

```
192-168-1-5:reactive-cli felixsatyaputra$ ./cli/target/scala-2.11/reactive-cli-out generate-deployment localhost:5001/foo/testimpl:1.0.0-SNAPSHOT --target kubernetes --kubernetes-version 1.6 --registry-tls-validation-disable
---
{"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"name":"testImpl-v1.0.0-SNAPSHOT","labels":{"app":"testImpl","appVersionMajor":"testImpl-v1","appVersionMajorMinor":"testImpl-v1.0","appVersion":"testImpl-v1.0.0-SNAPSHOT"}},"spec":{"replicas":1,"serviceName":"testImpl-v1","template":{"app":"testImpl","appVersionMajor":"testImpl-v1","appVersionMajorMinor":"testImpl-v1.0","appVersion":"testImpl-v1.0.0-SNAPSHOT"},"spec":{"containers":[{"name":"testImpl","image":"localhost:5001/foo/testimpl:1.0.0-SNAPSHOT","imagePullPolicy":"IfNotPresent","env":[{"name":"FOO","value":"123"},{"name":"RP_ENDPOINTS","value":"TA-V1"},{"name":"RP_ENDPOINTS_COUNT","value":"1"},{"name":"RP_ENDPOINT_0_PORT","value":"16668"},{"name":"RP_ENDPOINT_TA-V1_PORT","value":"16668"},{"name":"RP_KUBERNETES_POD_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}},{"name":"RP_KUBERNETES_POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"RP_PLATFORM","value":"kubernetes"},{"name":"RP_VERSION","value":"1.0.0-SNAPSHOT"},{"name":"RP_VERSION_MAJOR","value":"1"},{"name":"RP_VERSION_MINOR","value":"0"},{"name":"RP_VERSION_PATCH","value":"0"},{"name":"RP_VERSION_PATCH_LABEL","value":"SNAPSHOT"}],"ports":[{"containerPort":16668,"name":"ta-v1"}],"readinessProbe":{"httpGet":{"path":"/healthz","port":1234},"periodSeconds":60},"livenessProbe":{"exec":{"command":["/bin/bash","-c","exit 0"]}}}]}}}
---
{"apiVersion":"v1","kind":"Service","metadata":{"labels":{"app":"testImpl"},"name":"testImpl"},"spec":{"clusterIP":"None","ports":[{"name":"ta-v1","port":16668,"protocol":"TCP","targetPort":16668}],"selector":{"app":"testImpl"}}}
---
{"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"name":"testImpl"},"spec":{"rules":[{"http":{"paths":[{"path":"^/ta.*$","backend":{"serviceName":"ta-v1","servicePort":16668}}]}}]}}
```

**Comment by fsat** [comment]
**Manual Test: HTTPS with Basic Auth**

<pending>

**Comment by fsat** [comment]
**Manual Test: HTTPS with CA Info**

<pending>

**Comment by fsat** [comment]
Build previously failed due to `CURLOPT_XOAUTH2_BEARER` option not declared - I'd probably need to see which distro is causing this, and see whether this is really caused by older libcurl version.

If this is the case, we might need to generate manage the actual `Authorization` headers from the Scala binding 😞

**Comment by longshorej** [comment]
I don't think `libhttpsimple` should be aware of basic auth or tokens, just send them from Scala via headers. I'll PR what I mean.

**Comment by longshorej** [comment]
PR @ https://github.com/fsat/reactive-cli/pull/1 - feel free to use / incorporate into your solution if you agree with the idea.

**Pull request merged**
